@extends('layouts.admin')
@section('title','Caisse')
@section('content')
<div class="page-heading"><div><div class="eyebrow">TRÉSORERIE</div><h1 class="page-title">Caisse</h1><p class="page-sub">Suivez les entrées et sorties manuelles.</p></div><div><a class="btn btn-ghost" href="#closings">Historique Z</a><a class="btn btn-primary" href="{{ route('admin.cash.create') }}">+ Opération</a></div></div>
<div class="stats-grid"><div class="stat-card cyan"><div class="icon">↗</div><div class="value">{{ number_format($in,0,',',' ') }} F</div><div class="label">Total entrées</div></div><div class="stat-card amber"><div class="icon">↘</div><div class="value">{{ number_format($out,0,',',' ') }} F</div><div class="label">Total sorties</div></div><div class="stat-card violet"><div class="icon">◈</div><div class="value">{{ number_format($in-$out,0,',',' ') }} F</div><div class="label">Solde</div></div></div>
<div class="card" style="display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap"><div><strong>Clôture de journée</strong><div class="muted" style="font-size:12px">Enregistrez le Z de caisse du jour.</div></div><form method="POST" action="{{ route('admin.cash.close') }}">@csrf<button class="btn btn-primary">Clôturer la journée</button></form></div>
<div class="card"><div class="card-title">Opérations</div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Catégorie</th><th>Motif</th><th>Montant</th><th>Utilisateur</th></tr></thead><tbody>@forelse($ops as $op)<tr><td class="muted">{{ $op->created_at->format('d/m/Y H:i') }}</td><td><span class="badge {{ $op->type === 'in' ? 'active' : 'revoked' }}">{{ $op->type === 'in' ? 'Entrée' : 'Sortie' }}</span></td><td>{{ $op->category ?? '—' }}</td><td>{{ $op->reason }}</td><td class="amount-cell">{{ $op->type === 'in' ? '+' : '-' }}{{ number_format($op->amount,0,',',' ') }} F</td><td>{{ $op->user?->name }}</td></tr>@empty<tr><td colspan="6" class="table-empty">Aucune opération.</td></tr>@endforelse</tbody></table></div>{{ $ops->links() }}</div>
<div class="card" id="closings"><div class="card-title">Dernières clôtures</div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Entrées</th><th>Sorties</th><th>Ventes encaissées</th><th>Solde</th><th>Utilisateur</th></tr></thead><tbody>@forelse($closings as $closing)<tr><td>{{ $closing->closing_date->format('d/m/Y') }}</td><td>{{ number_format($closing->total_in,0,',',' ') }} F</td><td>{{ number_format($closing->total_out,0,',',' ') }} F</td><td>{{ number_format($closing->sales_collected,0,',',' ') }} F</td><td class="amount-cell">{{ number_format($closing->balance,0,',',' ') }} F</td><td>{{ $closing->user?->name }}</td></tr>@empty<tr><td colspan="6" class="table-empty">Aucune clôture.</td></tr>@endforelse</tbody></table></div></div>
@endsection
