@extends('layouts.admin')
@section('title', 'Nouvelle vente — ' . config('shop.name', 'StockFlow'))
@section('content')
<div class="page-heading"><div><div class="eyebrow">CAISSE</div><h1 class="page-title">Nouvelle vente</h1><p class="page-sub">Ajoutez plusieurs produits dans le panier.</p></div><a class="btn btn-ghost" href="{{ route('admin.sales.index') }}">← Ventes</a></div>
@if($errors->any())<div class="flash error"><ul style="margin-left:18px;">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><form method="POST" action="{{ route('admin.sales.store') }}">@csrf
<div id="cart"></div><button class="btn btn-ghost" type="button" onclick="addLine()">+ Ajouter un article</button>
<div class="form-grid" style="margin-top:18px"><div class="field"><label for="customer_id">Client enregistré</label><select class="input" id="customer_id" name="customer_id"><option value="">Client comptant</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }} {{ $customer->phone ? '· '.$customer->phone : '' }}</option>@endforeach</select></div><div class="field"><label for="amount_paid">Montant payé (FCFA) *</label><input class="input" id="amount_paid" type="number" name="amount_paid" min="0" value="0" required></div><div class="field"><label for="client_name">Nom client libre</label><input class="input" id="client_name" name="client_name"></div><div class="field"><label for="client_phone">Téléphone client</label><input class="input" id="client_phone" name="client_phone"></div></div>
<div class="sale-total-box">Total panier : <strong id="sale-total">0 F</strong></div><button class="btn btn-primary" type="submit">Valider la vente</button></form></div>
<script>const products=@json($products);let n=0;const money=v=>new Intl.NumberFormat('fr-FR').format(v)+' F';function addLine(){const i=n++;const wrap=document.createElement('div');wrap.className='cart-line';wrap.dataset.i=i;wrap.innerHTML=`<div class="field"><label>Produit</label><select class="input product-select" name="items[${i}][product_id]" required>${products.map(p=>`<option value="${p.id}" data-price="${p.sale_price}">${p.name} · stock ${p.quantity} · ${money(p.sale_price)}</option>`).join('')}</select></div><div class="field"><label>Quantité</label><input class="input qty-input" type="number" min="1" max="9999" value="1" name="items[${i}][quantity]" required></div><button class="btn btn-danger" type="button" onclick="this.closest('.cart-line').remove();calc()">Retirer</button>`;document.querySelector('#cart').appendChild(wrap);wrap.querySelectorAll('select,input').forEach(x=>x.addEventListener('input',calc));calc()}function calc(){let total=0;document.querySelectorAll('.cart-line').forEach(x=>{const s=x.querySelector('select');total+=Number(s.options[s.selectedIndex]?.dataset.price||0)*Number(x.querySelector('input').value||0)});document.querySelector('#sale-total').textContent=money(total)}addLine();</script>
@endsection
