@extends('layouts.admin')
@php($editing = $customer->exists)
@section('title', ($editing ? 'Modifier le client' : 'Nouveau client'))
@section('content')
<div class="page-heading"><div><div class="eyebrow">RELATION CLIENT</div><h1 class="page-title">{{ $editing ? 'Modifier le client' : 'Nouveau client' }}</h1><p class="page-sub">Les informations client peuvent être réutilisées lors d’une vente.</p></div><a class="btn btn-ghost" href="{{ route('admin.customers.index') }}">← Clients</a></div>
@if($errors->any())<div class="flash error"><ul style="margin-left:18px;">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><form method="POST" action="{{ $editing ? route('admin.customers.update', $customer) : route('admin.customers.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="form-grid"><div class="field"><label for="name">Nom *</label><input class="input" id="name" name="name" value="{{ old('name', $customer->name) }}" required></div><div class="field"><label for="phone">Téléphone</label><input class="input" id="phone" name="phone" value="{{ old('phone', $customer->phone) }}"></div><div class="field"><label for="email">Email</label><input class="input" id="email" type="email" name="email" value="{{ old('email', $customer->email) }}"></div><div class="field"><label for="price_tier">Niveau de prix</label><select class="input" id="price_tier" name="price_tier"><option value="retail" @selected(old('price_tier', $customer->price_tier ?: 'retail') === 'retail')>Détail</option><option value="wholesale" @selected(old('price_tier', $customer->price_tier) === 'wholesale')>Gros</option></select></div></div><div class="field"><label for="address">Adresse</label><input class="input" id="address" name="address" value="{{ old('address', $customer->address) }}"></div><div class="field"><label for="notes">Notes</label><textarea class="input" id="notes" name="notes" rows="4">{{ old('notes', $customer->notes) }}</textarea></div><button class="btn btn-primary" type="submit">{{ $editing ? 'Enregistrer les modifications' : 'Créer le client' }}</button></form></div>
@endsection
